export const browserCoreExamples = [
  "aura_intelligence browser status",
  "aura_intelligence browser start",
  "aura_intelligence browser stop",
  "aura_intelligence browser tabs",
  "aura_intelligence browser open https://example.com",
  "aura_intelligence browser focus abcd1234",
  "aura_intelligence browser close abcd1234",
  "aura_intelligence browser screenshot",
  "aura_intelligence browser screenshot --full-page",
  "aura_intelligence browser screenshot --ref 12",
  "aura_intelligence browser snapshot",
  "aura_intelligence browser snapshot --format aria --limit 200",
  "aura_intelligence browser snapshot --efficient",
  "aura_intelligence browser snapshot --labels",
];

export const browserActionExamples = [
  "aura_intelligence browser navigate https://example.com",
  "aura_intelligence browser resize 1280 720",
  "aura_intelligence browser click 12 --double",
  'aura_intelligence browser type 23 "hello" --submit',
  "aura_intelligence browser press Enter",
  "aura_intelligence browser hover 44",
  "aura_intelligence browser drag 10 11",
  "aura_intelligence browser select 9 OptionA OptionB",
  "aura_intelligence browser upload /tmp/file.pdf",
  'aura_intelligence browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "aura_intelligence browser dialog --accept",
  'aura_intelligence browser wait --text "Done"',
  "aura_intelligence browser evaluate --fn '(el) => el.textContent' --ref 7",
  "aura_intelligence browser console --level error",
  "aura_intelligence browser pdf",
];
